name: Build MelodyBrain Binaries

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job:
          - { target: x86_64-unknown-linux-gnu, pretty: linux-x86_64 }
          - { target: arm-unknown-linux-gnueabihf, pretty: linux-armv6 }
          - { target: armv7-unknown-linux-gnueabihf, pretty: linux-armv7 }
          - { target: aarch64-unknown-linux-gnu, pretty: linux-arm64 }
          - { target: riscv64gc-unknown-linux-gnu, pretty: linux-riscv64 }
          - { target: x86_64-apple-darwin, pretty: darwin-x86_64 }
          - { target: aarch64-apple-darwin, pretty: darwin-aarch64 }

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.job.target }}

    - name: Set up macOS cross-compiler
      if: contains(matrix.job.target, 'apple')
      uses: Timmmm/setup-osxcross@v2
      with:
        osx-version: "12.3"

    - name: Build binary
      run: |
        cross build --bin melodybrain-client --release --target ${{ matrix.job.target }}
        cp target/${{ matrix.job.target }}/release/melodybrain-client melodybrain
        tar -czf melodybrain.tar.gz melodybrain

    - name: Upload artifact
      uses: actions/upload-artifact@v6
      with:
        name: melodybrain-${{ matrix.job.pretty }}
        path: ./melodybrain.tar.gz
